import type { Metadata } from "next";
import { Radio_Canada, Geist, Geist_Mono } from 'next/font/google'
import "./globals.css";
import ClientLayout from "./ClientLayout";

const inter = Radio_Canada({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${geistSans.variable} antialiased`}>
      <body
        
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
