import type { Metadata } from "next";
import { Inter, Geist, Geist_Mono, Manrope, Poppins } from 'next/font/google'
import "./globals.css";
import ClientLayout from "./ClientLayout";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${poppins.variable} antialiased`}>
      <body
        className=""
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
